version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - './conf/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './react-app/static/:/srv/static'
    links:
      - 'uwsgi'
  migration:
    build:
      context: .
    volumes:
      - './:/srv/brandslist'
    entrypoint: python3 manage.py migrate
    depends_on:
      - 'postgres'
  uwsgi:
    build:
      context: .
    depends_on:
      - 'postgres'
    volumes:
      - './:/srv/brandslist'
  postgres:
    image: postgres:9-alpine
    restart: always
    environment:
      POSTGRES_USER: 'brands'
      POSTGRES_PASSWORD: 'vGa4LA1u33'
    volumes:
      - "brandsdb:/var/lib/postgresql/data"
volumes:
  brandsdb: