# Generated by Django 2.2 on 2019-04-16 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30, verbose_name='Наименование')),
                ('description', models.TextField(default='', verbose_name='Описание')),
            ],
        ),
    ]
